# Generated by Django 4.1 on 2022-09-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('movie_director', models.CharField(max_length=255)),
                ('movie_year', models.IntegerField()),
                ('movie_rating', models.IntegerField()),
                ('movie_description', models.TextField()),
                ('movie_imdb', models.URLField()),
            ],
        ),
    ]
