# Generated by Django 4.1 on 2022-09-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_imdb',
            new_name='movie_url',
        ),
    ]
