# Generated by Django 4.1 on 2022-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_mywatchlist_delete_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='watched',
            field=models.CharField(max_length=255),
        ),
    ]
